export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'body-max-line-length': [0, 'always'],
    'scope-enum': [
      2,
      'always',
      [
        'auth',
        'rbac',
        'audit',
        'intake',
        'widget',
        'matters',
        'documents',
        'schedule',
        'ics',
        'docs',
        'archive',
        'ocr',
        'rag',
        'email',
        'milestones',
        'dashboard',
        'admin',
        'ai',
        'db',
        'jobs',
        'infra',
        'ci',
        'design',
        'evals',
        'demo',
        'deps',
        'security',
      ],
    ],
  },
};
